linters:
  enable-all: true
  disable:
    - godox
    - godot
    - exhaustivestruct
    - gci
    - wrapcheck
    - gofumpt
    - ireturn
    - goerr113
    #deprecated
    - scopelint
    - maligned
    - interfacer
    - golint

issues:
  exclude-rules:
    - path: helpers.go
      linters:
        - gomnd
    - path: _test\.go
      linters:
        - bodyclose
        - funlen
        - goconst
        - dupl
        - lll
        - unparam
        - forcetypeassert
        - gocritic
        - contextcheck
        - varnamelen
        - gomnd
        - gochecknoglobals
    - path: mock\.go
      linters:
        - funlen
        - goconst
        - dupl
        - lll
        - unparam
        - forcetypeassert
        - gomnd

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
  varnamelen:
    max-distance: 5
    min-name-length: 3
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - w
      - r
