language: go
go:
  - 1.16.x

env:
  - LINT_VER=v1.43.0

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...
  - curl -sfL "https://raw.githubusercontent.com/golangci/golangci-lint/${LINT_VER}/install.sh" |
    sh -s -- -b "$(go env GOPATH)/bin" "${LINT_VER}"

script:
  - golangci-lint run
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
