language: go
go:
  - 1.16.x

env:
  - LINT_VER=1.43.0

git:
  depth: 1

notifications:
  email: false

before_install:
  - go get -t -v ./...
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/1.43.0/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0

script:
  - golangci-lint run
  - go test -v -race ./...
  - go test -covermode=count -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
